// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqpenmtsikdnigmswery.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcGVubXRzaWtkbmlnbXN3ZXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDk0NTYsImV4cCI6MjA3MTU4NTQ1Nn0.e-eoZjINlu4Pjru9wX62c5jyba-QFDtbcH8ii1jHhwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});